# Pre-commit hooks for Cartrita AI OS - Enhanced Security Configuration
repos:
  # Security scanning hooks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: detect-secrets
        description: "Detect secrets in codebase"
        args: ['--baseline', '.secrets.baseline']

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit
        description: "Security linter for Python"
        args: ["-r", "services/ai-orchestrator/", "-ll"]
        types: [python]

  - repo: local
    hooks:
      - id: security-audit
        name: Security Audit
        description: "Run custom security checks"
        entry: bash -c 'echo "Running security audit..."; if command -v safety >/dev/null 2>&1; then safety check --json; fi; if command -v npm >/dev/null 2>&1; then npm audit --audit-level high; fi'
        language: system
        pass_filenames: false
        stages: [commit]

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-ast
      - id: check-json
      - id: check-executables-have-shebangs

  # Python linting and formatting
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.2
    hooks:
      - id: pylint
        args: ["--fail-under=8.0"]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: ["--line-length=88"]

# Configuration
default_stages: [commit]
fail_fast: false
