global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ai-orchestrator"
    static_configs:
      - targets: ["ai-orchestrator:8000"]
    scrape_interval: 5s

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:3000"]
    scrape_interval: 5s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]

  # Redis metrics now collected via redis-exporter (avoids cross-protocol noise)
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 15s
    # Previous direct scrape of redis:6379 intentionally removed.
