name: Dependency Lock Verify

on:
  pull_request:
    paths:
      - 'services/ai-orchestrator/requirements.in'
      - 'services/ai-orchestrator/constraints.txt'
      - 'services/ai-orchestrator/requirements-gpu.in'
  workflow_dispatch:

jobs:
  verify-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: '3.13'

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Recompile constraints
        working-directory: services/ai-orchestrator
        run: |
          pip-compile --quiet --no-emit-options --no-annotate --generate-hashes --output-file constraints.new requirements.in

      - name: Diff constraints
        working-directory: services/ai-orchestrator
        run: |
          if ! diff -u constraints.txt constraints.new > constraints.diff; then
            echo 'Constraints drift detected. Please run pip-compile and commit updated constraints.txt'
            echo '--- DIFF ---'
            cat constraints.diff
            exit 1
          else
            echo 'Constraints up to date.'
          fi

      - name: Upload diff artifact (on failure)
        if: failure()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: constraints-diff
          path: services/ai-orchestrator/constraints.diff
